import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import 'bootstrap/dist/css/bootstrap.min.css';
import AddTodoForm from '../components/Todo/AddTodoForm';
import TodoList from '../components/Todo/TodoList';
import TotalCompleteItems from '../components/Todo/TotalCompleteItems';
import Link from 'next/link';
import toast from 'react-hot-toast';
import { Box } from '@chakra-ui/react'
import { useContext } from 'react';
import { UserContext } from '../lib/context';
import { useEffect } from 'react';
import { useSelector } from 'react-redux';

export default function Home() {
  const { user, username } = useContext(UserContext);


  return (
    <div className={styles.container}>
      <Head>
        <title>Redux NextJS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        {!username && (
          <div className={styles.welcome}>
            <h1>Please Login too see my project</h1>
            <h1>safe for sure!</h1>

          </div>

        )}

      </main>

    </div>
  )
}
