import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import 'bootstrap/dist/css/bootstrap.min.css';
import AddTodoForm from '../components/Todo/AddTodoForm';
import TodoList from '../components/Todo/TodoList';
import TotalCompleteItems from '../components/Todo/TotalCompleteItems';
import Link from 'next/link';
import toast from 'react-hot-toast';
import { Box } from '@chakra-ui/react'
import { useContext } from 'react';
import { UserContext } from '../lib/context';
import { useEffect } from 'react';
import { useSelector } from 'react-redux';

export default function TodoPage() {
    let isLogin = false;
    const { user, username } = useContext(UserContext);
    const count = useSelector((state) => state.counter.value)

    console.log(username);
    console.log(count);

    return (
        <div className={styles.container}>
            <Head>
                <title>Redux NextJS</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main >
                {username && (
                    <>
                        <h1 className={styles.title}>Jittipon.resume.website</h1>

                        {/* <button className='btn btn-success' onClick={() => toast.success('hello toast!')}>
          Toast Me
        </button> */}
                        <Link href="/Result" >
                            <a>another page</a>
                        </Link>

                        <AddTodoForm />
                        <TodoList />
                        <TotalCompleteItems />
                    </>
                )}

                {!username && count == 0 && (
                    <div className={styles.welcome}>
                        <h1>Loader</h1>

                    </div>

                )}



            </main>

        </div>
    )
}
