import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import 'bootstrap/dist/css/bootstrap.min.css';
import AddTodoForm from '../components/Todo/AddTodoForm';
import TodoList from '../components/Todo/TodoList';
import TotalCompleteItems from '../components/Todo/TotalCompleteItems';
import Link from 'next/link';
import toast from 'react-hot-toast';
import { Box } from '@chakra-ui/react'
import { useContext } from 'react';
import { UserContext } from '../lib/context';
import { useEffect } from 'react';
import { useSelector } from 'react-redux';
import { Spinner } from '@chakra-ui/react'

export default function TodoPage() {
    const { username } = useContext(UserContext);

    console.log(username);

    return (
        <div className={styles.container}>
            <Head>
                <title>Redux NextJS</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main >
                {username && (
                    <>
                        <h1 className={styles.title}>Jittipon.resume.website</h1>
                        <Link href="/Result" >
                            <a>another page</a>
                        </Link>

                        <AddTodoForm />
                        <TodoList />
                        <TotalCompleteItems />
                    </>
                )}

                {!username &&(
                    <div className={styles.welcome} style={{marginTop:"50rem"}}>
                        <Spinner
                            thickness='4px'
                            speed='0.65s'
                            emptyColor='gray.200'
                            color='blue.500'
                            size='xl'
                        />
                    </div>
                )}
            </main>
        </div>
    )
}
